(function() {
  'user strict';

  angular
    .module('sulekhaApp')
    .controller('HomeCtrl', HomeCtrl)
    .controller('BusinessCtrl', BusinessCtrl)
    .controller('AdminCtrl', AdminCtrl);
    HomeCtrl.$inject = ['$state'];

    function HomeCtrl($state) {
      var vm = this;
      vm.itemArray = [
        {id: 1, name: 'first'},
        {id: 2, name: 'second'},
        {id: 3, name: 'third'},
        {id: 4, name: 'fourth'},
        {id: 5, name: 'fifth'},
      ];

      vm.selected = { value: vm.itemArray[0] };
      vm.isHover = 0;
      vm.isShow = false;
      vm.index = 0;
      vm.togleCategory = function(index) {
        if (vm.index === index) {
          vm.isShow = !vm.isShow;
        } else {
          vm.isShow = true;
        }
        vm.index = index;
      };

      vm.categorys =
        [{title: 'Home & Office Services',
          listtab:
            [ {namesubtab: 'Home Appliance Dealers 11',
                listsubtab: [
                [{isTitle: true, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]},
              {namesubtab: 'Home/Office Appliance Services',
                listsubtab: [
                [{isTitle: true, name: '23222Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]},
              {namesubtab: 'Home/Office Appliance Services',
                listsubtab: [
                [{isTitle: true, name: '555Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]}
            ]
        },
        {title: 'Home Improvement',
          listtab:
            [ {namesubtab: 'Home Appliance Dealers 23 ',
                listsubtab: [
                [{isTitle: true, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]},
              {namesubtab: 'Home/Office Appliance Services 3',
                listsubtab: [
                [{isTitle: true, name: '23222Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]},
              {namesubtab: 'Home/Office Appliance Services 4',
                listsubtab: [
                [{isTitle: true, name: '555Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]}
            ]
        },
        {title: 'Properties & Rentals',
          listtab:
            [ {namesubtab: 'Home Appliance Dealers 23 ',
                listsubtab: [
                [{isTitle: true, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]},
              {namesubtab: 'Home/Office Appliance Services 3',
                listsubtab: [
                [{isTitle: true, name: '23222Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]},
              {namesubtab: 'Home/Office Appliance Services 4',
                listsubtab: [
                [{isTitle: true, name: '555Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]}
            ]
        },
        {title: 'Education & Training',
          listtab:
            [ {namesubtab: 'Home Appliance Dealers 23 ',
                listsubtab: [
                [{isTitle: true, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]},
              {namesubtab: 'Home/Office Appliance Services 3',
                listsubtab: [
                [{isTitle: true, name: '23222Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]},
              {namesubtab: 'Home/Office Appliance Services 4',
                listsubtab: [
                [{isTitle: true, name: '555Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]}
            ]
        },
        {title: 'Professional Services',
          listtab:
            [ {namesubtab: 'Home Appliance Dealers 23 ',
                listsubtab: [
                [{isTitle: true, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]},
              {namesubtab: 'Home/Office Appliance Services 3',
                listsubtab: [
                [{isTitle: true, name: '23222Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]},
              {namesubtab: 'Home/Office Appliance Services 4',
                listsubtab: [
                [{isTitle: true, name: '555Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]}
            ]
        },
        {title: 'Travel & Transport',
          listtab:
            [ {namesubtab: 'Home Appliance Dealers 23 ',
                listsubtab: [
                [{isTitle: true, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]},
              {namesubtab: 'Home/Office Appliance Services 3',
                listsubtab: [
                [{isTitle: true, name: '23222Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]},
              {namesubtab: 'Home/Office Appliance Services 4',
                listsubtab: [
                [{isTitle: true, name: '555Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]}
            ]
        },
        {title: 'Health & wellness',
          listtab:
            [ {namesubtab: 'Home Appliance Dealers 23 ',
                listsubtab: [
                [{isTitle: true, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]},
              {namesubtab: 'Home/Office Appliance Services 3',
                listsubtab: [
                [{isTitle: true, name: '23222Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]},
              {namesubtab: 'Home/Office Appliance Services 4',
                listsubtab: [
                [{isTitle: true, name: '555Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]}
            ]
        },
        {title: 'Events',
          listtab:
            [ {namesubtab: 'Home Appliance Dealers 23 ',
                listsubtab: [
                [{isTitle: true, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]},
              {namesubtab: 'Home/Office Appliance Services 3',
                listsubtab: [
                [{isTitle: true, name: '23222Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]},
              {namesubtab: 'Home/Office Appliance Services 4',
                listsubtab: [
                [{isTitle: true, name: '555Home Appliance Dealers'},
                {isTitle: false, name: 'Home/Office Appliance Services'},
                {isTitle: false, name: 'Home/Office Products'},
                {isTitle: false, name: 'AC Dealers'},
                {isTitle: false, name: 'Air Cooler Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}],
                [{isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'},
                {isTitle: false, name: 'Home Appliance Dealers'}]
              ]}
            ]
        },
        ];
    };

    BusinessCtrl.$inject = ['$state', '$firebaseArray'];
    function BusinessCtrl($state, $firebaseArray) {
        var ref = firebase.database().ref().child('business');
        var list = $firebaseArray(ref);
        vm = this;
        vm.information = {};

        vm.submit = function() {
            list.$add(vm.information);
        }
    };

    AdminCtrl.$inject = ['$state', '$firebaseArray'];
    function AdminCtrl($state, $firebaseArray) {
        var ref = firebase.database().ref().child('business');
        vm = this;
        vm.listBusiness = $firebaseArray(ref);

        vm.addBusiness = function() {
            vm.inserted = {
              email: '',
              company_name: '',
              phone: ''
            };
            vm.listBusiness.$add(vm.inserted)
        };

        vm.removeBusiness = function(index, id) {
            if (id) {
                var item = vm.listBusiness.$getRecord(id);
                vm.listBusiness.$remove(item);
            }
        };

        vm.saveBusiness = function(data, id) {
            if (id) {
                var item = vm.listBusiness.$getRecord(id);
                item.email = data.email;
                item.company_name = data.company_name;
                item.phone = data.phone;
                vm.listBusiness.$save(item);
            }
        };

    };
}());
